services:
    avathar.bbguild_lineage2.installer:
        class: avathar\bbguild_lineage2\game\lineage2_installer
        arguments:
            - '@dbal.conn'
            - '@cache.driver'
            - '@config'
            - '@user'

    avathar.bbguild_lineage2.provider:
        class: avathar\bbguild_lineage2\game\lineage2_provider
        arguments:
            - '@avathar.bbguild_lineage2.installer'
            - '@ext.manager'
        tags:
            - { name: bbguild.game_provider }
